### ISSUE TITLE
フォーマッタ適用(2)

### ISSUE THREAD

**Issue by botamochi0x12** [orukRed/tyranosyntax#162]
ワークスペース内の次のファイルをフォーマットしましょう：

- [x] TypeScript および JavaScript ファイルをフォーマットします：
    - [x] `eslint.config.mjs`
    - [x] `webpack.config.js`
    - [x] `src/subscriptions/**/*.ts` 
    - [x] `src/defineData/**/*.ts` 
    - [x] `src/test/**/*.ts`
    - [x] `src/extension.ts`
    - [x] `src/InformationExtension.ts`
    - [x] `src/InformationWorkSpace.ts`
    - [x] `src/Parser.ts`
    - [x] `src/TyranoLogger.ts`
- [x] この VSCode ワークスペースの設定ファイルをフォーマットします：
    - [x] `.vscode/*.json`
- [x] VSCode 拡張機能の設定ファイルをフォーマットします：
    - [x] `tsconfig.json`
    - [x] `snippet/*.json`
    - [x] `syntaxes/*.json`
    - [x] `package.json` の `contributes`
    - [x] `Tooltip/*.json`
    - [x] `language-configuration*.json`

手順：

1. （任意）`npm ci` または `npm install` を実行します。
2. （任意）`editor.formatOnSaveMode` の値を `modificationsIfAvailable` から特定のファイル拡張子（例：`[json]`）のために `files` に変更します。
3. フォーマットしたいファイルを開きます（例：`tsconfig.json` を開く）。
4. `Ctrl + P` を押してコマンド パレットを開きます。
5. ファイル上で「`Format Document (Forced)`」コマンドを実行します。
6. `.prettierignore` から関連する行を削除します（例：`tsconfig.json` の行を削除します）。

<details>
<summary>In English</summary>

Formatting the files below in the workspace:

- Format TypeScript and JavaScript files:
    - `eslint.config.mjs`
    - `webpack.config.js`
    - `src/**/*.ts`
    - `src/**/*.js` except `src/lib/tyrano_parser.js`
- Format configuration files for this VSCode workspace:
    - `.vscode/*.json`
- Format configuration files for the VSCode extension settings:
    - `tsconfig.json`
    - `snippet/*.json`
    - `syntaxes/*.json`
    - `contributes` in `package.json`
    - `Tooltip/*.json`
    - `language-configuration*.json`

Steps:

1. (Optional) Execute `npm ci` or `npm install`
2. (Optional) Change the value of `editor.formatOnSaveMode` from `modificationsIfAvailable` to `file` for a specific file extension (e.g. `[json]`)
3. Open the file needed to format (e.g. Open `tsconfig.json`)
4. Open the command palette by pressing `Ctrl + P`
5. Run the command `Format Document (Forced)` on the file
6. Remove any relevant lines from `.prettierignore` (e.g. remove line for `tsconfig.json`)

</details>

**Comment by botamochi0x12** [comment]
#163 で `tsconfig` をフォーマットしました

**Comment by orukRed** [comment]
>（ただし `src/lib/tyrano_parser.js` は除く）

上記文言を削除しました。
`src/lib/tyrano_parser.js`は現在未使用（Parser.tsに置き換え）なため、ファイルごと削除します。

**Comment by orukRed** [comment]
フォーマット必要なファイル一覧修正しました。
残りはsrc直下と、src/test**のみなのでそれに合わせて見やすくしています。

**Comment by orukRed** [comment]
すべて完了しました！
closeします 🙏
