### ISSUE TITLE
テキストのサジェストが効かない

### ISSUE THREAD

**Issue by bombastus1541** [orukRed/tyranosyntax#37]
v0.6.0からテキストのサジェスト（補完）が効かなくなっているようです。

**Comment by orukRed** [comment]
私の方でも確認してみたところ、おっしゃる通り効かなくなってることを確認しました。

ご連絡ありがとうございます。:bow:
調査の上、今後のアップデートで修正予定とします:thumbsup:

v0.5.4での実行結果
![image](https://user-images.githubusercontent.com/70902268/164707735-2eb4909f-dbc3-4f90-a85e-f6309d4c48d2.png)

v0.8.0での実行結果
![image](https://user-images.githubusercontent.com/70902268/164707950-2bfcde5a-8f60-4c90-8f45-cfb2bd0331a6.png)
